### ISSUE TITLE
[New Feature] Web interface?

### ISSUE THREAD

**Issue by liusida** [yoland68/comfy-cli#3]
If allow me to guess, I think the key to `ComfyUI-Manager`'s popularity is its user-friendly web interface, which allows users to manage custom nodes without leaving the browser. Is there a plan to develop a web interface for comfy-cli as well? It would be great to have a website where I could launch and manage multiple ComfyUI instances and monitor their performance.

Just brain storming. 😄

**Comment by liusida** [comment]
![launchunrealengine-windows](https://github.com/Comfy-Org/comfy-cli/assets/14249458/305ac77c-8ea9-4334-b044-807deb557f08)

As an example.

**Comment by robinjhuang** [comment]
@liusida Are you talking about launching instances on Cloud Providers? Or locally?

**Comment by liusida** [comment]
> @liusida Are you talking about launching instances on Cloud Providers? Or locally?

Hi, @robinjhuang. My intention is to use ComfyUI on servers with powerful GPUs. However, it might also be helpful when used locally, since Unreal Engine uses it for launching local instances, as do many other software applications.

**Comment by justinclitheroe** [comment]
That sounds out of scope to me, it would be pretty simple to create a frontend that utilizes the cli to quickly spin up installations

That said, comfy itself already has the ability to run multi user, is there a benefit to having separate installs of comfy on one machine?

**Comment by liusida** [comment]
I've tried to use multi-user in ComfyUI, but when it comes down to install custom nodes, there will be conflicts.
Users obviously perfer different custom nodes, and many nodes don't build with multi-user in mind.

I wish to only share downloaded models, but not the whole system with settings.

As you said, create a frontend that utilizes this cli is a good idea. Let's see if that'll develop into another project.

**Comment by liusida** [comment]
Interestingly, I found this project yesterday:
https://github.com/ComfyWorkflows/ComfyUI-Launcher

I discovered it while collecting the Top 100 starred ComfyUI-related GitHub repositories and going through them:
https://github.com/liusida/top-100-comfyui/

However, ComfyUI-Launcher installs one ComfyUI instance for each workflow. It feels like a bit of overkill, but it does solve the conflict problem with different nodes, I guess.
