### ISSUE TITLE
Version check is broken when installed through pip

### ISSUE THREAD

**Issue by wouterdebie** [yoland68/comfy-cli#42]
**Describe the bug**
When the package is installed through pip, the version check for upgrading comfy-cli doesn't work. There seem to be two issues: 
1. pyproject.toml isn't present in the package
2. Even if would be packaged, `get_version_from_pproject()` reads from the current directory, not relative to where the package is installed.

**To Reproduce**

```bash
# start with a clean pyenv
pyenv virtualenv 3.10.14 comfytest
pip install comfy-cli
comfy install
```

This shows `None` as the currently installed version.

**Expected behavior**
Current version to be `0.0.22` and not getting the upgrade warning.

**Comment by wouterdebie** [comment]
@ltdrdata nice, thanks!

**Comment by yoland68** [comment]
@wouterdebie Is this fixed for you in new version? Gonna close it if so 🙏

**Comment by wouterdebie** [comment]
Yes, thanks!
