### ISSUE TITLE
Command line completion for node install/uninstall/etc

### ISSUE THREAD

**Issue by wouterdebie** [yoland68/comfy-cli#46]
Command line completion only works up to commands and doesn't include the actual list of nodes one can install/uninstall/fix/etc. It'd be nice to complete to an actual node that I want to install. 

I also noticed that additional arguments for `comfy node show` like ` [installed|enabled|not-installed|disabled|all|snapshot|snapshot-list]` are not completed either.

**Comment by ltdrdata** [comment]
Autocompletion has been applied except for node handling. Node processing will require various additional implementations, so it will be implemented later.

**Comment by ltdrdata** [comment]
You need recent ComfyUI-Manager to use node name completion.

**Comment by wouterdebie** [comment]
@ltdrdata awesome! When are you pushing a new version?

**Comment by yoland68** [comment]
@wouterdebie will push new version today

Minor issue for @ltdrdata: these are failing silently on my end when right after install: https://github.com/yoland68/comfy-cli/commit/5c71cfee094f4c9419f6ee6a6bab14f86445ca7c#r142014466

```
/Users/yoland/opt/anaconda3/envs/comfycli-dev/bin/python: can't open file '/Users/yoland/comfy/ComfyUI/custom_nodes/ComfyUI-Manager/cm-cli.py': [Errno 2] No such file or directory
```
Is there a specific exception you are trying to ignore here?

**Comment by ltdrdata** [comment]
> /Users/yoland/opt/anaconda3/envs/comfycli-dev/bin/python



> @wouterdebie will push new version today
> 
> Minor issue for @ltdrdata: these are failing silently on my end when right after install: [5c71cfe#r142014466](https://github.com/yoland68/comfy-cli/commit/5c71cfee094f4c9419f6ee6a6bab14f86445ca7c#r142014466)
> 
> ```
> /Users/yoland/opt/anaconda3/envs/comfycli-dev/bin/python: can't open file '/Users/yoland/comfy/ComfyUI/custom_nodes/ComfyUI-Manager/cm-cli.py': [Errno 2] No such file or directory
> ```
> 
> Is there a specific exception you are trying to ignore here?

My draft was cache updating in the completer code.
So, I though it will be annoying if error occurs during completion.

But, it is useless policy now since the code is separated from completer.
